### ISSUE TITLE
Try to formalize the code a bit more instead of using VAR<number>

### ISSUE THREAD

**Issue by AkechiShiro** [d4t4s3c/Shelly#1]

**Comment by d4t4s3c** [comment]
Thanks for the recommendation friend! any suggestions?

**Comment by AkechiShiro** [comment]
Well use meaningfull variable, use associate bash array/or just bash arrays, I prefer full caps variables, but it's just a personal thing

I would do one array per functions (for the paylods)

**Comment by AkechiShiro** [comment]
I would've liked also if I could do ./shelly -d 0 -i <PUBLIC_IP> -p <PORT> -l <shell_TYPE>

**Comment by AkechiShiro** [comment]
I did write something along those line in a custom script will send you a gist at some point

**Comment by AkechiShiro** [comment]
Additionnaly : https://bertvv.github.io/cheat-sheets/Bash.html
And use :  https://github.com/koalaman/shellcheck in CI/CD GitHub Actions for every commits, failure on warning if you want to maintain high standard code, maybe you can ignore some warning too

**Comment by AkechiShiro** [comment]
I could implement the CI/CD thing but my time is limited.

**Comment by d4t4s3c** [comment]
thanks my friend! I'm a little busy, but I'll look at it in the future.

**Comment by AkechiShiro** [comment]
I'll try to help when I can to, hope you can still stay afloat on open source stuff ! Good luck with your efforts, man !
